name: Scheduled Lottery Execution

on:
  schedule:
    - cron: '0 12 * * *' 
  workflow_dispatch:  # 添加此行，允许手动触发

jobs:
  run-lottery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 安装任何其他需要的依赖
          # pip install -r requirements.txt

      - name: Run lottery script
        run: |
          python lottery_script.py
